config/routes.rb
Rails.application.routes.draw do
  resources :restaurants do
    resources :reviews
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  CATEGORY = ["chinese", "italian", "japanese", "french", "belgian"]
  has_many :reviews, dependent: :destroy
  validates :phone_number, presence: true
  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true, inclusion: { in: CATEGORY }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, presence: true, :inclusion =>  0..5, :numericality => {:only_integer => true}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :destroy, :update]
 def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
     restaurant = Restaurant.new(restaurants_params)
    if restaurant.save
      redirect_to restaurants_path
    end
  end

  def edit

  end

  def update
    @restaurant.update(restaurant_params)
    redirect_to restaurants_path
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    redirect_to restaurants_path
  end

private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

private

  def review_params
    params.require(:review).permit(:content, :rating)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
  <%= simple_form_for (@restaurant) do |r| %>
    <%= r.input :name %>
    <%= r.input :address %>
    <%= r.input :phone_number %>
    <%= r.input :category, selected: "chinese", collection: %w(chinese italian japanese belgian french) %>
    <%= r.button :submit %>
  <% end %>

app/views/restaurants/edit.html.erb
<%= render 'form', restaurant: @restaurant %>

app/views/restaurants/index.html.erb
<% @restaurants.each do |restaurant| %>
  <%= link_to restaurant.name, restaurant %>
  <%= restaurant.address %>
  <%= restaurant.phone_number %>
  <%= restaurant.category %>

  <%= link_to "Delete", restaurant_path(restaurant),
      method: :delete,
      data: { confirm: "Are you sure?" } %><br>
<% end %>

 <%= link_to "New restaurant", new_restaurant_path %>

app/views/restaurants/new.html.erb
<%= render 'form', restaurant: @restaurant %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>
<h2><%= @restaurant.address %></h2>
<h3><%= @restaurant.phone_number %></h3>
<h4><%= @restaurant.category %></h4>

<%= link_to "Home-page", restaurants_path %>
<%= link_to "Edit restaurant", edit_restaurant_path(params[:id]) %>
<%= link_to "Add a review", new_restaurant_review_path(@restaurant) %>

<% @restaurant.reviews.each do |review|%>
  <h1><%= review.content %></h1>
  <h1><%= review.rating %></h1>
<% end %>

app/views/reviews/new.html.erb
  <h1> Add your review! </h1>
  <%= simple_form_for [@restaurant, @review] do |r| %>
    <%= r.input :content %>
    <%= r.input :rating %>
    <%= r.submit "Post" %>
  <% end %>